name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --python 3.8 --deploy --ignore-pipfile

      # - name: Run tests
      #   run: |
      #     pipenv run python manage.py test

      - name: Deploy to EC2
        env:
          AWS_PEM_KEY: ${{ secrets.AWS_PEM_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
        run: |
          echo "${{ secrets.AWS_PEM_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/backend_arquitectura_project
            git pull origin main
            pipenv install --python 3.8 --deploy --ignore-pipfile
            pipenv run python manage.py migrate
            sudo systemctl restart apache2
          EOF
