name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --python 3.12 --deploy --ignore-pipfile

      # - name: Run tests
      #   run: |
      #     pipenv run python manage.py test

      - name: Create SSH Key File
        run: |
          echo "${{ secrets.AWS_PEM_KEY }}" > key.pem
          chmod 600 key.pem
          ls -l key.pem
          cat key.pem

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AWS_PEM_KEY }}

      - name: Test SSH Connectivity
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ vars.AWS_HOST }} "echo 'SSH Connection Successful'"

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ vars.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/backend_arquitectura_project
            git pull origin main
            pipenv install --python 3.12 --deploy --ignore-pipfile
            pipenv run python manage.py migrate
            sudo systemctl restart django
            sudo systemctl restart apache2
          EOF
